# build environment
FROM node:alpine
# Make dirs
RUN mkdir /app
RUN mkdir /app/node_modules
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY . ./
RUN npm install
RUN npm config set unsafe-perm true
RUN npm install react-scripts@1.1.1 -g
RUN npm install serve -g

ARG NODE_ENV=production
ARG REACT_APP_BUTTER_CMS_TOKEN

ENV NODE_ENV={$NODE_ENV}
ENV REACT_APP_BUTTER_CMS_TOKEN={$REACT_APP_BUTTER_CMS_TOKEN}

COPY . /usr/src/app
RUN npm run build
# build environment

CMD ["serve", "build"]
