version: "3"

networks:
  web:
    external: true
  internal:
    external: false

services:
  portfolio:
    container_name: portfolio
    build:
      context: .
      dockerfile: Dockerfile-prod
      args:
        - REACT_APP_BUTTER_CMS_TOKEN=4cdbbe9df44593599957e9e3784fc46bedc8089a
    ports:
      - "5000:5000"
    labels:
      - traefik.frontend.rule=Host:eetuk.fi,www.eetuk.fi
      - traefik.docker.network=web
      - traefik.port=5000
    networks:
      - internal
      - web
